spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaithfb6v72LW4HR0h7
            client-secret: xhMYc-ndkud1kEImsUlpfEiL0g8uRl8ZYsL3vS7k
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-621737.oktapreview.com/oauth2/default
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    protocol: smtp
    test-connection: false

  profiles:
    active: @spring.profiles.active@


